version: "3.8"

services:
  meetly:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: meetly_dev
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - POSTGRES_CONN_STRING=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@auth_postgres:5432/${POSTGRES_DB}?sslmode=disable
      - RABBITMQ_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672/
      - CONFIRMATION_QUEUE=${CONFIRMATION_QUEUE}
    ports:
      - "18080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started
    networks:
      - meetly_network_dev
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: meetly_db_dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "45432:5432"
    networks:
      - meetly_network_dev
    volumes:
      - meetly_pg_data_dev:/var/lib/postgresql/data

  mail_service:
    build:
      context: .
      dockerfile: ./services/mail/Dockerfile
    container_name: mail_service_dev
    environment:
      - RABBITMQ_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672/
      - CONFIRMATION_QUEUE=${CONFIRMATION_QUEUE}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME}
      - SMTP_FROM_ADDRESS=${SMTP_FROM_ADDRESS}
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - meetly_network_dev
    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: meetly_minio_dev
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "19000:9000"
      - "19001:9001"
    networks:
      - meetly_network_dev
    volumes:
      - minio_data_dev:/data

  loki:
    image: grafana/loki:2.10.0
    container_name: loki
    ports:
      - "13100:13100"
    command: -config.file=/etc/loki/local-config.yml
    volumes:
      - ./loki-data:/loki

  promtail:
    image: grafana/promtail:2.10.0
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - ./promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana:10.1.0
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
    ports:
      - "13000:13000"
    depends_on:
      - loki

volumes:
  meetly_pg_data_dev:
  rabbitmq_data_dev:
  minio_data_dev:
  kong:

networks:
  meetly_network_dev:
    driver: bridge